@ 삭제
selim0915/react-study pull request #4
Opened 2023-02-02 07:41 UTC by srwoo2

2023-02-02 07:41 UTC, srwoo2 reviewed
review

2023-02-02 07:44 UTC, selim0915 approved these changes
ok

2023-02-03 04:31 UTC, srwoo2 reviewed
안녕하세요

2023-02-03 04:31 UTC, srwoo2 reviewed
PR test

2023-02-03 04:35 UTC, selim0915 approved these changes

2023-02-03 04:35 UTC, selim0915 approved these changes

2023-02-03 04:36 UTC, selim0915 requested changes
변경 요청

2023-02-03 04:36 UTC, selim0915 approved these changes
재 승인

2023-02-03 04:40 UTC, merged